# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4d85599c682a516a784ce0000201d56fe6d71885f8e6fc62749dee1721544eabdf714801327e696e77c69248d0585794df9c6e1b192d012fc7dd1d33b5bbe2

test:
  secret_key_base: 1db1d70a8a306d6dbc3e67055da9d55f2036da3c7cc7f2736082bc1443e5359c71e94805fda1859cad36a0bc80ffebf9a172b85c65b61ed80d5895a918687e3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
